# Linear Regression Model on Housing Dataset predicting price

## Import Libraries

In [29]:
import pandas as pd
import numpy as np
import matplotlib as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

## Load Dataset

In [30]:
dataset = pd.read_csv('Housing.csv')
dataset.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [31]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

## Convert Categorical Variables

In [32]:
yes_no_cols = ['mainroad','guestroom','basement',
               'hotwaterheating','airconditioning','prefarea']

for col in yes_no_cols:
    dataset[col] = dataset[col].map({'yes':1, 'no':0})

In [33]:
if 'furnishingstatus' in dataset.columns:
    dataset = pd.get_dummies(dataset, columns=['furnishingstatus'], drop_first=True)

In [34]:
X = dataset.drop('price', axis=1)
y = dataset['price']

## Train Test Split

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

## Feature Scaling

In [36]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## Build Linear Regression Model

In [37]:
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [38]:
y_pred = lr.predict(X_test)

## Model Evaluation

In [39]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

In [40]:
print("MAE :",mae)
print("MSE :",mse)
print("RMSE :",rmse)
print("R^2 Score:",r2)

MAE : 892294.9491502057
MSE : 1586758224575.701
RMSE : 1259665.91784318
R^2 Score: 0.6221280430074461

In [41]:
coeff_dr = pd.DataFrame(lr.coef_,X.columns, columns=['Coefficient'])
coeff_dr.sort_values(by='Coefficient',ascending=False)

                                   Coefficient
bathrooms                        527232.920622
area                             519732.503184
stories                          417377.560665
airconditioning                  310671.716613
prefarea                         256108.673668
basement                         229999.092047
parking                          224549.191856
hotwaterheating                  194805.264992
mainroad                         151504.871724
guestroom                        123633.150040
bedrooms                          67336.059263
furnishingstatus_semi-furnished  -37027.939716
furnishingstatus_unfurnished    -180911.225780

# Logistic Regression on Titanic dataset for survival prediction

## Data Wrangling

In [42]:
# libraries already imported
titanic_data = pd.read_csv('Titanic-Dataset.csv')
titanic_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [43]:
titanic_data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [44]:
titanic_data.drop("Cabin",axis=1,inplace=True)
titanic_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [45]:
titanic_data.dropna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [56]:
Sex = pd.get_dummies(titanic_data['Sex'],drop_first=True)
Sex.head()

    male
0   True
1  False
2  False
3  False
4   True

In [57]:
Embarked = pd.get_dummies(titanic_data['Embarked'],drop_first=True)
Embarked.head()

       Q      S
0  False   True
1  False  False
2  False   True
3  False   True
4  False   True

In [58]:
Pcl = pd.get_dummies(titanic_data['Pclass'],drop_first=True)
Pcl.head(5)

       2      3
0  False   True
1  False  False
2  False   True
3  False  False
4  False   True

In [59]:
titanic_data = pd.concat([titanic_data,Pcl,Embarked,Sex],axis=1)
titanic_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,2,3,Q,S,male
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,False,True,False,True,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,False,False,False,False,False
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,False,True,False,True,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,False,False,False,True,False
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,False,True,False,True,True

## Train Data

In [85]:
X = titanic_data.drop('Survived', axis=1)
y = titanic_data['Survived']

In [87]:
from sklearn.model_selection import train_test_split

In [89]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [90]:
from sklearn.linear_model import LogisticRegression

In [91]:
logmodel = LogisticRegression()

In [93]:
logmodel = LogisticRegression(max_iter=1000, solver="liblinear")
logmodel.fit(X_train.to_numpy(), y_train.to_numpy())

LogisticRegression(max_iter=1000, solver='liblinear')

In [103]:
predictions = logmodel.predict(X_test.to_numpy())

In [105]:
from sklearn.metrics import classification_report
classification_report(y_test, predictions)

'              precision    recall  f1-score   support\n\n           0       0.80      0.88      0.84       175\n           1       0.80      0.68      0.74       120\n\n    accuracy                           0.80       295\n   macro avg       0.80      0.78      0.79       295\nweighted avg       0.80      0.80      0.80       295\n'

In [106]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,predictions)

array([[154,  21],
       [ 38,  82]])

In [107]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,predictions)

0.8